import pygame

# Display settings
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 830
AGENT_NAME_FONT = 'comicsans'
AGENT_NAME_FONT_SIZE = 20
NUM_DISPLAYED_ON_LEADERBOARD = 5

# Game settings
BOARD_WIDTH = 1600
BOARD_HEIGHT = 830
FOOD_MASS = 1
GAME_MASS = 20000
MAX_FOOD = 200

MAX_VIRUSES = 5
VIRUS_MASS = 100
CELL_CONSUME_MASS_FACTOR = 1.1
VIRUS_CONSUME_MASS_FACTOR = 1.33  # how much larger one has to be to eat a virus

WHITE_COLOR = ((255, 255, 255))
VIRUS_COLOR = ((125, 250, 91))
VIRUS_OUTLINE_COLOR = ((112, 226, 81))

SHOOT_MASS = 10
MIN_MASS_TO_SHOOT = 50
MIN_MASS_TO_SPLIT = 100
AGENT_STARTING_MASS = 20
AGENT_STARTING_SPEED = 10
NUM_AI = 2
SPLIT_LIMIT = 16  # max number of individual cells a single agent can have

UP = 'UP'
UP_RIGHT = 'UP_RIGHT'
RIGHT = 'RIGHT'
DOWN_RIGHT = 'DOWN_RIGHT'
DOWN = 'DOWN'
DOWN_LEFT = 'DOWN_LEFT'
LEFT = 'LEFT'
UP_LEFT = 'UP_LEFT'
